/** Stable semantic selectors for native automation; do not use coordinates. */
export const testIds = {
  auth: { email: 'auth-email', submit: 'auth-send-link', language: 'auth-language' },
  legal: {
    consent: 'legal-current-consent',
    submit: 'legal-accept-current',
    terms: 'legal-terms-link',
    privacy: 'legal-privacy-link',
  },
  onboarding: {
    next: 'onboarding-next',
    back: 'onboarding-back',
    submit: 'onboarding-submit',
    country: 'onboarding-country',
    countrySheet: 'onboarding-country-sheet',
    ageConfirm: 'onboarding-age-confirm',
    legalConsent: 'onboarding-legal-consent',
  },
  daily: { reset: 'daily-reset', deck: 'daily-hero-deck', pop: 'daily-pop-mode', primary: 'daily-primary-action' },
  you: {
    profile: 'you-tab-profile',
    matching: 'you-tab-private',
    settings: 'you-tab-settings',
    countrySheet: 'matching-country-sheet',
    countrySearch: 'matching-country-search',
    countryApply: 'matching-country-apply',
    photoGuide: 'profile-photo-guide',
    updateLocation: 'profile-update-location',
  },
  settings: {
    blocked: 'settings-blocked-members',
    blockedTitle: 'settings-blocked-title',
    notifications: 'settings-notifications',
    delete: 'settings-delete-account',
    deleteDialog: 'settings-delete-dialog',
  },
  recap: { compatibility: 'compatibility-breakdown', open: 'recap-open-connection' },
  gallery: { close: 'gallery-close', recovery: 'gallery-recovery' },
  chat: {
    call: 'chat-call',
    safety: 'chat-safety',
    composer: 'chat-composer',
    send: 'chat-send',
    retry: 'chat-retry-pending',
  },
  safety: {
    menu: 'relationship-safety-menu',
    sheet: 'relationship-safety-sheet',
    report: 'relationship-safety-report',
    block: 'relationship-safety-block',
    confirmBlock: 'relationship-safety-confirm-block',
    retry: 'relationship-safety-retry',
    done: 'relationship-safety-done',
    reason: (reason: string) => `relationship-safety-reason-${reason}`,
  },
} as const;
